Adjusted src/Makefile to run **/selftest.sh scripts.

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -31,6 +31,11 @@ TESTMODS = $(shell find . -regex '[^\#]*\.lua' -printf '%P ' | \
              xargs grep -l '^function selftest *[[:punct:]]' | \
              sed -e 's_\.lua__' -e 's_/_._g')
 
+# TESTSCRIPTS expands to:
+#   lib/watchdog/selftest.sh ...
+# for each executable selftext.sh script in src.
+TESTSCRIPTS = $(shell find . -name "selftest.sh" -executable | xargs)
+
 PATH := ../deps/luajit/usr/local/bin:$(PATH)
 
 all: snabb
@@ -49,11 +54,11 @@ snabb: $(LUAOBJ) $(HOBJ) $(COBJ) $(ASMOBJ)
 	@ln -fs snabb snabbswitch
 	@ls -sh snabb
 
-test: $(TESTMODS)
+test: $(TESTMODS) $(TESTSCRIPTS)
 
 test_ci: FAIL_ON_FIRST="true"
 
-test_ci: $(TESTMODS)
+test_ci: $(TESTMODS) $(TESTSCRIPTS)
 
 $(TESTMODS): testlog snabb
 	$(E) "TEST      $@"
@@ -67,6 +72,23 @@ $(TESTMODS): testlog snabb
 		|| ( \
 			echo "ERROR     testlog/$@"; \
 			echo "EXITCODE: $$EXITCODE" >> testlog/$@; \
+			if [ -n "$(FAIL_ON_FIRST)" ]; then exit $$EXITCODE; fi;\
+		) \
+	)
+
+testlog = testlog/$(shell echo "$(@)" | sed -e 's_/_._g')
+$(TESTSCRIPTS): testlog snabb
+	$(E) "TEST      $@"
+	$(Q) ./$@ > $(testlog) || ( \
+		EXITCODE="$$?"; \
+		[ "$$EXITCODE" -eq $(TEST_SKIPPED) ] \
+		&& ( \
+			echo "SKIPPED   $(testlog)"; \
+			echo "EXITCODE: $$EXITCODE" >> $(testlog); \
+		) \
+		|| ( \
+			echo "ERROR     $(testlog)"; \
+			echo "EXITCODE: $$EXITCODE" >> $(testlog); \
 			if [ -n "$(FAIL_ON_FIRST)" ]; then exit $$EXITCODE; fi;\
 		) \
 	)
